---
    - name: Install Nginx
      apt: name=nginx state=latest update_cache=true
      register: nginxinstalled
      notify:
         - nginx start

    - name: Add Nginx config
      when: nginxinstalled is success
      template: src=default.j2 dest=/etc/nginx/sites-available/default owner=www-data group=www-data

    - name: Create Root Directory for Nginx
      when: nginxinstalled is success
      file: path={{ root }}  mode=775 state=directory owner=www-data group=www-data
      notify:
          - nginx restart
