---
    - name: Install base needed apt-packages
      apt:
        pkg:
          - python3
          - python3-dev
          - python3-virtualenv
          - python3-pip
          - tcl-dev
          - tk-dev
          - python3-tk
          - git
          - virtualenv
            #        vars: 
            #          - ansible_python_interpreter: /usr/bin/python3
        state: latest
