---
   - name: Creates directory
     file: path={{project_name_path}} state=directory

   - name: Install Django Framework
     pip:
        name: django==2.2.2
        virtualenv: "{{project_name_path}}/env"
        virtualenv_command: virtualenv
        virtualenv_python: python3

   - name: Instal python library for PSQL
     pip:
        name: psycopg2
        virtualenv: "{{project_name_path}}/env"
        virtualenv_command: virtualenv
        virtualenv_python: python3

   - name: Install a django project
     command: "{{ project_name_path }}/env/bin/django-admin.py startproject {{ project_name }} chdir={{ project_name_path }}/"

   - name: Create Settings File for Django
     template: src=settings.py.j2 dest={{ project_name_path }}/{{ project_name }}/{{ project_name }}/settings.py

   - name: Make migrations
     shell: "{{project_name_path}}/env/bin/python3 {{ project_name_path }}/{{ project_name }}/manage.py makemigrations"

   - name: Migrate database
     django_manage: app_path={{ project_name_path }}/{{ project_name }}
                        command=migrate
                        virtualenv={{project_name_path}}/env

   - name: Get all static files
     django_manage: app_path={{ project_name_path }}/{{ project_name }}
                        command=collectstatic
                        virtualenv={{project_name_path}}/env
