---
    - name: Install PostgreSQL
      apt:
        pkg:
          - postgresql
          - postgresql-contrib
          - postgresql-server-dev-all
          - python3-psycopg2
          - python-psycopg2
        state: latest

    - name: Start and enable postgres
      service: name=postgresql enabled=yes state=started

    - name: Create database
      postgresql_db: name={{ db_name }}
      become_user: postgres
      become: yes

    - name: Create user
      postgresql_user: db={{ db_name }}
                       name={{ db_user }}
                       password={{ db_password }}
                       priv=ALL
                       state=present
                       encrypted=yes
                       role_attr_flags=NOSUPERUSER,NOCREATEDB
      become: yes
      become_user: postgres
